### ISSUE TITLE
Error: Creating default object from empty value

### ISSUE THREAD

**Issue by agendartobias** [nitsan-technologies/ns_feedback#1]
Hey, when i install ns_feedback extension, include typoscript in static and go to "NS Feedback" module and click on root page i get this error:

`
PHP Warning: Creating default object from empty value in /var/www/vhosts/typo10_local/typo3conf/ext/ns_feedback/Classes/NsTemplate/TypoScriptTemplateConstantEditorModuleFunctionController.php line 136
`

I am using TYPO3 10.4.18 and PHP 7.4

**Comment by nitsan-technologies** [comment]
Hello there

FYI, We have resolved this issue and deployed the latest changes. Please download/update the extension and let's know if you are still facing any issues.

Thanks!
Team NITSAN
