### ISSUE TITLE
Error for globalVar = LIT:1 - Expression could not be parsed.

### ISSUE THREAD

**Issue by agendartobias** [nitsan-technologies/ns_feedback#2]
Hey, every page refresh on frondend it get this error:

`Wed, 13 Jul 2022 08:02:48 +0200 [ERROR] request="a34155c78894d" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"globalVar = LIT:1 = 1"}`

The problem is in file setup.typoscript (line 63) - https://github.com/nitsan-technologies/ns_feedback/blob/81d6d5eac55ac897673bee9c47f9c30315c4e5ac/Configuration/TypoScript/setup.typoscript#L63

This must be migrated from: [globalVar = LIT:1 = {$myConstant}] to [{$myConstant} == 1]

But in line 60 you have correct definition. Can you just delete old syntax?

**Comment by nitsan-technologies** [comment]
Hello @agendartobias 
Greetings of the day!

Thanks for reporting this issue. We have resolved this issue in our latest release. Please download the latest version.

Thanks!
Team NITSAN
