### ISSUE TITLE
Wrong CSS class selector in nsfeedback.js

### ISSUE THREAD

**Issue by agendartobias** [nitsan-technologies/ns_feedback#8]
Hey,

the definition of CSS class selector for feedback box is wrong:

https://github.com/nitsan-technologies/ns_feedback/blob/a4ad626cdf394bbe1a117904dcc58f88cc3975d1/Resources/Public/JavaScript/nsfeedback.js#L29 - instead of .global-ns-feedback you have .tx-ns-feedback defined in template

**Comment by nitsan-technologies** [comment]
Hey @agendartobias ,

Thanks for the valuable feedback
The issue with the selector has been fixed.  Please download the latest version.

Team @nitsan-technologies
